In [ ]:
# %pip install numpy matplotlib

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

## Indexing Multidimensional Arrays

Numpy arrays work the same way as other sequences, but they can have multiple dimensions (rows, columns, etc) over which to index/slice the array.

```python
data = np.array([[0, 1, 2,  3],
                 [4, 5, 6,  7],
                 [8, 9, 10, 11]]
               )
second_row = data[1, :]
third_column = data[:, 2]
element_second_row_third_column = data[1, 2]
```

**Exercises**

Using the example dataset *scores*, select only the described elements from each list:

In [ ]:
scores = np.arange(1, 49).reshape(6, 8)
scores

**Example:** The first score in the 2nd row:

In [ ]:
scores[1, 0]

The fourth score in the first row:

the second score in the fifth row:

The third score in the sixth column:

The third-through-fifth columns:

The first-through-fourth columns:

The second-through-fourth **rows**:


## Working with Images

Image data is stored as a 3D matrix, storing the brightness of each pixel along 3 coordinates:

  0. Which row the pixel is in  (between 0 and the height of the image)
  1. Which column the pixel is in (betweeen 0 and the width of the image)
  2. What color channel the pixel is in (red, green, blue, and sometimes alpha)

White pixels usually have the highest brightness values, and black pixels the darkest.

If you zoom in enough, you can see the square grid.  For example, as we zoom in on this heart we start to see the square pixels that make it up:

<img src="https://www.pinclipart.com/picdir/middle/531-5317564_heart-pixel-art-8-bit-heart-png-clipart.png" width="300">

This means that visualizing any image in Python can be done by "plotting" a matrix!  
Let's load an image and visualize it onscreen using Matplotlib, a plotting library.  Working with images generally uses these 3 functions:

| Function | Purpose  | Example |
| :----:   | :----:   | :---:   |
| **`plt.imread()`** | Loads a image from a filename  | `plt.imread("brian.png")` |
| **`plt.imshow()`** | Plots a multidimensional array as an image | `plt.imshow(my_image_array)` |
| **`plt.imsave()`** | Saves an array as an image on the computer | `plt.imsave("new_image.jpg", my_array)` |



In [ ]:
from os import makedirs, mkdir
from PIL import Image
from urllib.request import urlopen
from pathlib import Path
from io import BytesIO

savedir = Path("images")
savedir.mkdir(exist_ok=True)
urls = [
    ("http://www.bio.umass.edu/microscopy/images/gfpxxx1.jpg", "cells.jpg"),
    ("https://medievalists.gumlet.io/wp-content/uploads/2015/04/Favourite-Scene-from-Monty-Python-and-the-Holy-Grail.jpg", "montypython.jpg"),
    ("https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Skull_and_brain_normal_human.svg/800px-Skull_and_brain_normal_human.svg.png", "skull.png"),
    ("https://upload.wikimedia.org/wikipedia/commons/f/f1/MultiPhotonExcitation-Fig10-doi10.1186slash1475-925X-5-36-clipping.JPEG", "intestine.jpg")
]
for url, filename in urls:
    downloaded_data = urlopen(url).read()
    inmemory_file = BytesIO(downloaded_data)
    img = Image.open(inmemory_file)
    img.save(savedir / filename)


**Exercises**

**Example**: Read and Plot the Skull image in the `images` folder.

In [ ]:
im = plt.imread('images/skull.png')
plt.imshow(im)

Read and plot the mouse intestine image in the images folder:

Read and plot the "Cells" image in the images folder.

**Example**: Using the Cells image, index only the first 50 rows of the image and plot it, then save it as "top_part.png".  (This is called "cropping" an image)

In [ ]:
cropped = im[:50, :]
plt.imshow(cropped);
plt.imsave("top_part.png", cropped)

Crop and Plot only the left cluster of cells, then save the image as "left_cluster.png".

Crop and Plot only the right cluster of cells, then save the image as "right_cluster.png".

## Analyzing Image Data: Examining Each Channel of a Color Image

Flourescent imaging is made so that each color channel contains data from a different source.  Matrices represent Color images put this data into its own axis.  In matplotlib, the color channel is the third axis, with the data ordered RGB channels.


For the section on separating channels, here's a markdown table summarizing the methods used along with one-line explanations:

| Code | Description |
| ------ | ----------- |
| `channel = image[:,:,0]` | Extracts the first channel (red in an RGB image) from the image array. |
| `plt.imshow(channel, cmap='gray')` | Displays a single channel (grayscale) image with a specified colormap. |


**Exercises**

Each of the exercises below use a two-photon image of a mouse intestine.  In this image, red channels label actin filaments, the green label cell nuclei, and the blue cells label goglet cells.

In [ ]:
image = plt.imread('images/intestine.jpg')
plt.imshow(image);


**Example** Plot only red channel, using the "gray" colormap.

In [ ]:
image = plt.imread('images/intestine.jpg')
red_channel = image[:, :, 0]
plt.imshow(red_channel, cmap='gray');
# plt.colorbar();  # Show a reference colorbar.

Plot only the green channel, using the "gray" colormap.

Plot only the blue channel, using the "gray" colormap.

Plot only the blue channel, using the "viridis" colormap.

Plot only the green channel, using the "magma" colormap.

### Aggregating Across Axes

| Function | Method |
| :---  | :--- |
| `np.mean(x, axis=0)` | `x.mean(axis=0)` |
| `np.std(x, axis=0)`  | `x.std(axis=0)`  |
| `np.median(x, axis=0)` | *(No median method)* |

Almost all of the Numpy aggregation functions have an **axis** option, which lets you limit the operation to just that axis.  

For example, to get the mean of all columns:

```python
>>> array = np.arange(12).reshape(3, 4)
>>> array.mean(axis=0)
array([4., 5., 6., 7.])
```

And the mean of the rows:

```python
>>> array.mean(axis=1)
array([1.5, 5.5, 9.5])
```

Notice that the number of dimensions goes down by default whenever you aggregate across the axis.  If you'd like to keep the dimensions the same, you can also use the **keepdims=True** option:

```python
>>> array.mean(axis=1, keepdims=True)
array([[1.5],
       [5.5],
       [9.5]])
```

**Exercises**: Try it out for yourself, with the provided array `data`:

In [ ]:
np.random.seed(42)
data = np.random.randint(0, 10, size=(5, 3)) * [1, 10, 100]
data

In [ ]:
np.shape(data)

*Example*: What is the mean of each column?

In [ ]:
data.mean(axis=0)

What is the standard deviation of each row?

What is the maximum of each column?

What is the mean of each column's median?

What is the standard deviation of all the numbers in the matrix?

What is the maximum of each row?